myproj/myapp/urls.py
'''
Created on Jun 2, 2015

'''
from django.conf.urls import patterns, url
from myapp import views
from myapp.models import Course
from django.conf.urls import patterns, url
from myapp.genviews import IndexView, CreateView, DetailView
from myapp import genviews
'''
urlpatterns = patterns('',
        url(r'^$', views.index, name='index'),
        url(r'^about', views.about, name='about'),
        url(r'^detail/(?P<course_no>\d{3})$', views.detail, name='detail'),
        url(r'^topic/$',views.topics,name='topic'),
        url(r'^addtopic', views.addtopic, name='addtopic'),
        url(r'^topics/(?P<topic_id>\d+)$', views.topicdetail, name='topicdetail'),
        url(r'^user_logout', views.user_logout, name='user_logout'),
        url(r'^user_login', views.user_login, name='user_login'),
        url(r'^mycourses', views.mycourses, name='mycourses'),
        )
'''
urlpatterns = patterns('',
        url(r'^$', genviews.IndexView.as_view(),name='index'),
        url(r'^about', views.about, name='about'),
        url(r'^(?P<course_no>\d{3})$', genviews.DetailView.as_view(), name='detail'),
        url(r'^topic/$',views.topics,name='topic'),
        url(r'^addtopic/$',genviews.CreateView.as_view(),name='addtopic'),
        #url(r'^addtopic', views.addtopic, name='addtopic'),
        url(r'^topics/(?P<topic_id>\d+)$', views.topicdetail, name='topicdetail'),
        url(r'^topicdetail/(?P<topic_id>\d+)$', views.topicdetail, name='topicdetail'),
        url(r'^detail/(?P<course_no>\d{3})$', DetailView.as_view(model = Course, template_name='myapp/detail.html')),
        url(r'^user_logout',views.user_logout,name='user_logout'),
        url(r'^user_login',views.user_login,name='user_login'),
        url(r'^mycourses',views.mycourses,name='mycourses'),
        )

myproj/myproj/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from myapp import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^myapp/', include('myapp.urls', namespace = 'myapp')),
    
]

myproj/myapp/models.py
from django.db import models
from django.contrib.auth.models import User
#from _overlapped import NULL

# Create your models here.

class Student(models.Model):
    user=models.OneToOneField(User, primary_key=True)
    student_id = models.IntegerField() 
    UNDERGRAD = 1
    MSC = 2
    PHD = 3
    LEVEL_CHOICES = (
        (UNDERGRAD, 'Undergrad'),
        (MSC, 'Masters'),
        (PHD, 'PhD')
    )
    
    level = models.IntegerField(default=UNDERGRAD, choices=LEVEL_CHOICES)
    
    def list_of_course(self):
                return ', '.join([course.title for course in self.course_set.all()])
    def __str__(self):
                return '%s %s' % (self.user.first_name, self.user.last_name)
    '''
    level = models.IntegerField(default=UNDERGRAD, choices=LEVEL_CHOICES)

    def __str__(self):
        return self.user.first_name + " " + self.user.last_name
    
 #   def list_of_course(self):
    def __courselist__(self):
        return [course.title for course in course.object.all()] 
    def course(self):
        return Course.objects.filter(student=self)

    def course(self):
        return ourse.objects.filter(student=self)

    def list_of_course(self):
        return [course.title for course in course.objects.all()]
'''    
class Instructor(models.Model):
    user = models.OneToOneField(User, primary_key=True)
    webpage = models.URLField()
    office = models.CharField(max_length=50, default='EH120')
    
    def __str__(self):
        return self.user.first_name + " " + self.user.last_name 

class Author(models.Model): 
    fname = models.CharField(max_length=50)
    lname = models.CharField(max_length=50)
    #age = models.IntegerField( default = None)
    birthday = models.DateField(default = '1991-01-31')
    #city = models.CharField(max_length=20)
    country = models.CharField(max_length=20, default = 'Canada')
    
    def __str__(self):
        return self.fname

class Book(models.Model): 
    title = models.CharField(max_length=100)
    numpages = models.IntegerField()
    in_stock = models.BooleanField(default = 1)
    authors = models.ManyToManyField(Author)
    pubyear = models.IntegerField( default = None)
    def __str__(self):
        return self.title

class Course(models.Model):
    course_no = models.IntegerField(primary_key = True)
    title = models.CharField(max_length=100)
    textbook = models.ForeignKey(Book)
    instructor=models.ForeignKey(Instructor, null=True)
    student=models.ManyToManyField(Student)
    
    def __str__(self):
        return str(self.course_no)

class Topic(models.Model):
    subject = models.CharField(max_length=100, unique=True)   
    intro_course = models.BooleanField(default=True)
    NO_PREFERENCE = 0
    MORNING = 1
    AFTERNOON = 2
    EVENING = 3
    TIME_CHOICES = (
        (0, 'No preference'),
        (1, 'Morning'),
        (2, 'Afternoon'),
        (3, 'Evening')
    )
    time = models.IntegerField(default=0, choices=TIME_CHOICES)
    num_responses = models.IntegerField(default=0)
    avg_age =models.IntegerField(default=20)
    
    def __str__(self):
        return self.subject
    

myproj/myapp/forms.py
from django import forms
from myapp.models import Topic
from django.forms.widgets import RadioSelect, Textarea
class TopicForm(forms.ModelForm):
    class Meta:
        model= Topic
        fields=['subject', 'intro_course', 'time', 'avg_age']
        widgets={'time': RadioSelect}
        labels={
                'time': 'Preferred Time',
                'avg_age': 'What is your age',
                'intro_course':'This should be an introductory level course'
                }
class InterestForm(forms.Form):
    interested= forms.TypedChoiceField(widget=RadioSelect, coerce=int, choices= ((0, 'No '),(1, 'Yes')))
    age=forms.IntegerField(initial=20)
    comments=forms.CharField(widget=Textarea,label='Additional Comments',)

myproj/myapp/views.py
from django.shortcuts import render, get_object_or_404
# Import necessary classes
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response
from myapp.models import Course, Book, Author, Topic, Student, Instructor
from django.shortcuts import get_object_or_404
from myapp.forms import TopicForm, InterestForm
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, user_passes_test

from django.template import RequestContext 
from django.template import RequestContext 
from datetime import datetime

# Create your views here.
auth = User.objects.all()

def index(request):        
    # This is your index view function
    
    # Access db to get list of courses. limit 10
   courselist = Course.objects.all()[:10]        
   response = HttpResponse()        
   # Create empty response object
   
   #Send list of courses to template file
   return render_to_response('myapp/index.html', {'courselist': courselist,'auth':auth, 'user':request.user})

   # For each course, create a str to write to response
   '''
   for course in courselist:
        para = '<p>' + str(course) + '</p>'      
        # This is the new string response.write(para) # Add each str as a <p> to response obj
        response.write(para)
   #return response
    '''
'''
def about(request):
    return render_to_response('myapp/about.html', {'user':request.user})
    #return HttpResponse("This APP let you view and select courses to register in.")
'''
def about(request):
    '''
    request.session.set_test_cookie()
    '''
    c=RequestContext(request)
    visits = int(request.COOKIES.get('visits', '0'))
    if 'last_visit' in request.COOKIES:
        last_visit = request.COOKIES['last_visit']
        last_visit_time = datetime.strptime(last_visit[:-7], "%Y-%m-%d %H:%M:%S")
        if (datetime.now() - last_visit_time).seconds > 0:
            response =render_to_response('myapp/about.html',{'visits':visits+1},c)
            response.set_cookie('visits', visits+1)
            response.set_cookie('last_visit', datetime.now())
    else:
        response =render_to_response('myapp/about.html',{'visits':visits+1},c)
        response.set_cookie('visits', visits+1)
        response.set_cookie('last_visit', datetime.now())
    
    return response
@login_required
def detail(request,course_no):
    #courselist1=Course.objects.all()[:10]
    a = get_object_or_404(Course,course_no=course_no)
    #response=HttpResponse()
    '''
    for course in courselist1:
        if((int(course_no) == int(course.course_no))):
                   
            para = '</p>'+'<br>'+str(course.course_no)+'<br>'+str(course.title)+'<br>'+str(course.textbook)+'</p>'
            response.write(para)
    return response
    '''
    return render_to_response('myapp/detail.html', {'course':a,'auth':auth,'user':request.user})

def topics(request):
    topiclist = Topic.objects.all()[:10]
    return render(request, 'myapp/topic.html', {'topiclist':topiclist,'auth':auth,'user':request.user})

def addtopic(request):
    topiclist = Topic.objects.all()
    if request.method=='POST':
        form = TopicForm(request.POST)
        if form.is_valid():
            topic = form.save(commit=False)
            topic.num_responses=1
            topic.save()
            return HttpResponseRedirect(reverse('myapp:topic'))
    else:
        form=TopicForm()
    return render(request, 'myapp/addtopic.html', {'form':form, 'topiclist':topiclist,'auth':auth,'user':request.user})

def topicdetail(request, topic_id):
    topic= get_object_or_404(Topic, id=topic_id)
    if request.method=='POST':
        form= InterestForm(request.POST)
        
        if form.is_valid():
            if (form.cleaned_data['interested']== 1):
                print("hello!")
                a=form.cleaned_data['age']
                topic.avg_age=(topic.avg_age*topic.num_responses)
                topic.num_responses+=1
                topic.avg_age=(topic.avg_age+a)/topic.num_responses
                topic.save()
        return HttpResponseRedirect(reverse('myapp:topic'))
    else:
        form=InterestForm()
        return render(request, 'myapp/topicdetail.html', {'form':form, 'topic':topic,'auth':auth, 'user':request.user})
    
def user_login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password) 
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('myapp:index'))
            else:
                return HttpResponse('Your account is disabled.')
        else:
            return HttpResponse('Invalid login details.') 
    else:
        return render(request, 'myapp/login.html', {'user':request.user})

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse(('myapp:index')))
'''
@login_required
def mycourses(request):
    student=hasattr(request.user, 'student')
    if student:
        courselist = Course.objects.filter(student__user=request.user)
        response = HttpResponse()        # Create empty response object
        template='myapp/index.html'
        return render_to_response(template, {'courselist': courselist,'user':request.user},)
    for course in courselist:
        para = '<p>' + str(course) + '</p>'      # This is the new string         
        response.write(para) # Add each str as a <p> to response obj
        return response    
    else:
        return HttpResponse("You are not a student.")
'''
@login_required
def mycourses(request):
    stu=Student.objects.filter(user=request.user)
    
    try:
        courselist=Course.objects.filter(student=stu)
    except ValueError:
        print()
    
    message="You are not a student!"  
    
    return render(request,'myapp/mycourses.html' , {'user':request.user, 'courselist': courselist, 'message': message }, )

myproj/myapp/templates/myapp/about.html
{% extends 'myapp/base.html' %}
{% block body_block %}
	<!-- <p>This is the about page!</p> -->
	<!-- <p>Number of hits: {{visits}}</p> -->
	<div class="model">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        
        <h4 class="modal-title">About</h4>
      </div>
      <div class="modal-body">
        <p>This is ABOUT PAGE.</p>
      </div>
      
    </div>
  </div>
</div>


<ul class="nav nav-pills">
  <li class="active"><a href="#">Page Hits<span class="badge">{{visits}}</span></a></li>
  </ul> 
{% endblock %}

myproj/myapp/templates/myapp/about_old.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Course Selection APP</title>
</head>
<body>

	<p>This is the about page!</p>

<p><a href="/myapp">Home page</a></p>
</body>
</html>

myproj/myapp/templates/myapp/addtopic.html
{% extends 'myapp/base.html' %}

{% block body_block %}
<form action="{% url 'myapp:addtopic' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>
{% endblock %}

myproj/myapp/templates/myapp/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <style>
    
    
        html,
        body {
          height: 100%;
          /* The html and body elements cannot have any padding or margin. */
        }
        
        #nav {
          
            width: 100%;
         
            position: fixed;
          
          
          }
        
        
        /* Wrapper for page content to push down footer */
        #wrap {
          min-height: 100%;
          height: auto;
          /* Negative indent footer by its height */
          margin: 0 auto -60px;
          /* Pad bottom by footer height */
          padding: 0 0 60px;
        }
        
        /* Set the fixed height of the footer here */
        #footer {
            background: #005596 none repeat scroll 0 0;
            bottom: -20px;
            color: #fff;
            
            left: 0;
            margin: 40px 0 0;
          
            position: fixed;
            width: 100%;
            z-index: 499;
          
          }
        
        .pull-right {
        display: inline-block;
        margin: 0.5em;
        padding: 0.5;
        color: white;
        text-align: center;
}


a:LINK{
color: inherit;
}
        
        
        /* Custom page CSS
        -------------------------------------------------- */
        /* Not required for template or sticky footer method. */
        
        .container {
          width: auto;
          max-width: 680px;
          padding: 0 15px;
        }
        .container .credit {
          margin: 20px 0;
        }
                
    </style>
    <title> Group#9 Project </title>

    <!-- Bootstrap core CSS -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.1/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="style.css" rel="stylesheet">

  </head>

  <body>

    <!-- Wrap all page content here -->
    <div id="wrap">

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Group#9</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Search</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">{% block myhdg %}Hi, {{user.first_name}} {% endblock %}</a></li>
                <li> {% if user.is_authenticated  %}
           <a  class="btn btn-danger"  href = "{% url 'myapp:user_logout' %}"> Logout</a>

        
        
         {% else %}
           
                 <a  class="btn btn-primary"  href="{% url 'myapp:user_login' %}">Login</a>
                
             
            {% endif %}</li>
      </ul>
    </div>
  </div>
</nav>

      <!-- Begin page content -->
      <div class="container" >

        <div class="page-header">
          <h1>Welcome</h1>
        </div>
        
          
     {% block body_block %}*** {% endblock %}</br></br>
    
           
      </div>
    </div><!-- Wrap Div end -->

    <div id="footer"  >
   
        <div class="panel panel-primary" style="text-align: center;" >
  <div class="panel-heading">
    <h3 class="panel-title"><a class="btn btn-link" href="/myapp/about">About</a>
               <a class="btn btn-link" href="/myapp/topic">Topics</a>
                <a class="btn btn-link" href="/myapp/addtopic">New Topic</a>
                <a class="btn btn-link" href="/myapp/mycourses">My courses</a>
               <a class="btn btn-link" href = "{% url 'myapp:index' %}">Main Page</a></h3>
  </div>
 
</div>
        
        
        

        
        
     
    </div>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
  </body>
</html>

myproj/myapp/templates/myapp/detail.html
{% extends 'myapp/base.html' %}
{% block body_block %}
	<li> {{course.course_no }} </li>
	<li> {{course.textbook }} </li>
	<li> {{course.title }} </li>		
			
	
{% endblock %}

myproj/myapp/templates/myapp/detail_old.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Course Selection APP</title>
</head>
<body>

	<li> {{course.course_no }} </li>
	<li> {{course.textbook }} </li>
	<li> {{course.title }} </li>		
			
				
	<p><a href="/myapp">Home page</a></p>
	<p><a href="{% url 'myapp:about' %}">About page</a></p>
	
</body>
</html>

myproj/myapp/templates/myapp/index.html
{% extends 'myapp/base.html' %}

{% block body_block %}
{% if user.is_authenticated  %}<h4><span class="label label-success"> Today's Lucky Number: {{luckynum}}</span> </h4> {% endif %}
<h2>List of Available Courses</h2>

<div class="list-group">
<a href="#" class="list-group-item active"> <h4>List of Available Courses</h4> </a>
 

<br>
   {% if courselist %}
     
       {% for course in courselist %}
       
    

 <a href="{% url 'myapp:detail' course.course_no %}" class="list-group-item">{{ course.title }} : {{ course.course_no }}
 </a>



       	

           
       {% endfor %}
   </div>
   {% else %}
       <strong>There are no available courses!</strong>
   {% endif %}
  
   {% if user.is_authenticated  %}
   <ul class="nav nav-pills">
  <li class="active"><a href="#">Visits<span class="badge">{{index_visits}}</span></a></li>
  </ul>   {% endif %}
   
{% endblock %}

myproj/myapp/templates/myapp/index_old.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Course Selection APP</title>
</head>
<body>
    <h2>List of Available Courses</h2>
    {% if courselist %}
    
        {% for course in courselist %}
			<h4><a href="{% url 'myapp:detail' course.course_no %}">{{ course.title }}</h4>
			<li><a href="{% url 'myapp:detail' course.course_no %}">{{ course.course_no }}</li>
			        	
			
            
        {% endfor %}
    
    {% else %}
        <strong>There are no available courses!</strong>
    {% endif %}

<p><a href="{% url 'myapp:about' %}">About page</a></p>
</body>
</html>

myproj/myapp/templates/myapp/login.html
	<!DOCTYPE html>
<html>
<head>
<meta charset="ISO-8859-1">
<title>Login</title>
 <link rel="stylesheet" href="/static/myapp/styleN.css">
</head>
<body>
	<!-- <form action="{% url 'myapp:user_login' %}" method="post">
	 {% csrf_token %}
    	Username: 	<input type="text" name="username">
    	Password: 	<input type="password" name="password">
    				<input type="submit" value="OK"> 

    </form>
    -->
    
      <div class="wrapper">
	<div class="container">
		<h1>Welcome</h1>
		
		<form action="{% url 'myapp:user_login' %}" method="post">{% csrf_token %}
			<input  type="text" name="username" maxlength="100" id="id_username"  placeholder="Username">
			<input type="password" name="password" maxlength="100" id="id_password"  placeholder="Password">
			<input type="submit" value="Submit"  />
			
		</form>
	</div>
	
	<ul class="bg-bubbles">
		<li></li>
		<li></li>
		<li></li>
		<li></li>
		<li></li>
		<li></li>
		<li></li>
		<li></li>
		<li></li>
		<li></li>
	</ul>
</div>
    <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>

        <script src="/static/js/index.js"></script>
    
</body>
</html>

myproj/myapp/templates/myapp/mycourses.html
{% extends 'myapp/base.html' %}

{% block body_block %}
<body>
	{% for course in courselist %}
		{{course.course_no}}
		<br>
		{{course.title}}
		<br>
		<br> 
	{% endfor %}
</body>
{% endblock %}

myproj/myapp/templates/myapp/topic.html
{% extends 'myapp/base.html' %}
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Topic</title>
</head>
<body>

{% block body_block %}
	<!-- <b>Topic:
	<br>
	<br> -->
	{% if topiclist %}
	<table class="table table-striped table-hover ">
  <thead>
    <tr>
       <th>Topic Name</th>
    </tr>
  </thead>
  <tbody>
    	{% for topic in topiclist %}
    <tr>
      <td><a href="{% url 'myapp:topicdetail' topic.id %}">{{topic}} </a></b></td>
    </tr>
    {% endfor %}
    	  </tbody>
</table> 

<script>
    var tables = document.getElementsByTagName('table');
    var table = tables[tables.length - 1];
    var rows = table.rows;
    for(var i = 0, td; i < rows.length; i++){
        td = document.createElement('td');
        td.appendChild(document.createTextNode(i + 1));
        rows[i].insertBefore(td, rows[i].firstChild);
    }
</script>
    {% else %}
    <strong>Oops, There are no available topics!!</strong>
    {% endif %}
<br>
<a href = "{% url 'myapp:addtopic' %}">Add Topic</a>




{% endblock %}
 
 </body>
 </html>
 
 </body>
 </html>

myproj/myapp/templates/myapp/topicdetail.html
{% extends 'myapp/base.html' %}

{% block body_block %}
<h2>Topic Detail Page</h2>

<p class="text-success">Subject : </b>{{topic.subject}} </p>
<p class="text-primary">No. of people interested : {{topic.num_responses}} </p>
<p class="text-warning">Is it a introductory course? : {{topic.intro_course}}  </p>
<p class="text-in	fo"> Average age is : {{topic.avg_age}} </p>

<!-- <a href="{% url 'myapp:index' %}">Index</a></p>
<a href="{% url 'myapp:about' %}">About page</a>
<a href = "{% url 'myapp:addtopic' %}">Add Topic</a>
 -->
 <form class="form-horizontal" action="{% url 'myapp:topicdetail' topic.id%}" method="post">
  <fieldset>
    <legend>Show Your Interest in this Topic</legend>
    <div class="form-group">
      {% csrf_token %}
    	{{ form.as_p }}
    </div>
      
   <div class="form-group">
      <div class="col-lg-10 col-lg-offset-2">
        <button type="reset" class="btn btn-default">Reset</button>
        <button type="submit" class="btn btn-primary">Submit</button>
      </div>
    </div>
  </fieldset>
</form>
 
 

    
   


{% endblock %}